apiVersion: apps/v1
kind: Deployment
metadata:
  name: robust_planner-deployment
spec:
  selector:
    matchLabels:
      app: robust_planner
  replicas: 1
  template:
    metadata:
      labels:
        app: robust_planner
    spec:
      containers:
      - name: robust_planner
        image: gregunz/robustplanner
        ports:
        - containerPort: 80
